flask_app/routes.py
# 3rd-party packages
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    Blueprint,
    session,
    g,
)
from flask_mongoengine import MongoEngine
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename

# stdlib
from datetime import datetime
import io
import base64

# local
from . import bcrypt, movie_client
from .forms import (
    SearchForm,
    MovieReviewForm,
    RegistrationForm,
    LoginForm,
    UpdateUsernameForm,
)
from .models import User, Review, load_user
from .utils import current_time


main = Blueprint("main", __name__)


""" ************ View functions ************ """


@main.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("main.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)


@main.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = movie_client.search(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("main.index"))

    return render_template("query.html", results=results)


@main.route("/movies/<movie_id>", methods=["GET", "POST"])
def movie_detail(movie_id):
    try:
        result = movie_client.retrieve_movie_by_id(movie_id)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("main.login"))

    form = MovieReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.title,
        )
        review.save()

        return redirect(request.path)

    reviews = Review.objects(imdb_id=movie_id)

    return render_template(
        "movie_detail.html", form=form, movie=result, reviews=reviews
    )


@main.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)

    return render_template("user_detail.html", username=username, reviews=reviews)


""" ************ User Management views ************ """


@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("main.login"))

    return render_template("register.html", title="Register", form=form)


@main.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("main.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("main.login"))

    return render_template("login.html", title="Login", form=form)


@main.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@main.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        # current_user.username = username_form.username.data
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("main.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Hey, {{ current_user.username }}!</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('main.user_detail', username=current_user.username) }}">
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Movie Reviews</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Movie Reviewer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
    <div class="col">
        <h2>Please use the search bar to search for movies! Then you can review them </h2>
    </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('main.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/movie_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if movie %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ movie.title }} ({{ movie.year }})
      </div>
      <div class="card-body">
        <img src="{{ movie.poster_url }}" class="mr-3 movie" alt="alt text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Directed by:</b> {{ movie.director }}</li>
          <li class="list-group-item"><b>Actors:</b> {{ movie.actors }}</li>
          <li class="list-group-item"><b>Genres:</b> {{ movie.genres }}</li>
          <li class="list-group-item"><b>Awards:</b> {{ movie.awards }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('main.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <img src="{{ result.poster_url }}" class="mr-3 movie" alt="missing">
        <div class="media-body">
        <h5 class="mt-0"><a href="{{ url_for('main.movie_detail', movie_id=result.imdb_id) }}">{{ result.title }}</a> ({{ result.year }})</h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('main.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Reviews</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
        <ul class="media-list">
            {% for review in reviews %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('main.movie_detail', movie_id=review.imdb_id) }}">
                            {{ review.movie_title }}
                        </a>
                    </strong>
                    <p>
                        {{ review.content }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}